name: "代理服务"
version: "1.0.0"
slug: "proxy_service"
description: "临时代理服务，用于远程升级Home Assistant"
url: "https://github.com/symi-daguo/ha-proxy-addon"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
startup: application
boot: manual
ports:
  7890/tcp: 7890
  7890/udp: 7890
  7891/tcp: 7891
  7891/udp: 7891
ports_description:
  7890/tcp: "HTTP代理端口"
  7890/udp: "HTTP代理端口"
  7891/tcp: "SOCKS代理端口"
  7891/udp: "SOCKS代理端口"
options:
  subscription_type: "clash"
  subscription_url: ""
  clear_config: true
schema:
  subscription_type: "list(clash|shadowrocket)"
  subscription_url: "str"
  clear_config: "bool"
hassio_api: true
ingress: true
panel_icon: "mdi:earth"
panel_title: "代理服务" 