version: "1.0.0"
slug: "proxy_service"
name: "Proxy Service"
description: "Temporary proxy service for Home Assistant remote upgrade"
url: "https://github.com/symi-daguo/ha-proxy-addon"
init: false
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
image: "ghcr.io/symi-daguo/{arch}-addon-proxy"
map:
  - config:rw
  - ssl:rw
ports:
  7890/tcp: 7890
  7891/tcp: 7891
ports_description:
  7890/tcp: "HTTP proxy port"
  7891/tcp: "SOCKS proxy port"
host_network: true
privileged:
  - NET_ADMIN
  - NET_RAW
hassio_api: true
hassio_role: default
ingress: true
ingress_port: 7890
panel_icon: "mdi:earth"
panel_title: "Proxy Service"
webui: "http://[HOST]:[PORT:7890]"
version_regex: "^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\+([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?$"