name: "Proxy Service"
version: "1.0.0"
slug: "proxy_service"
description: "Temporary proxy service for Home Assistant remote upgrade"
url: "https://github.com/symi-daguo/ha-proxy-addon"
image: "ghcr.io/symi-daguo/{arch}-addon-proxy"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
startup: application
boot: manual
host_network: true
privileged:
  - NET_ADMIN
  - NET_RAW
map:
  - config:rw
  - ssl:rw
ports:
  7890/tcp: 7890
  7891/tcp: 7891
ports_description:
  7890/tcp: "HTTP proxy port"
  7891/tcp: "SOCKS proxy port"
options:
  subscription_type: "clash"
  subscription_url: ""
  clear_config: true
schema:
  subscription_type: "list(clash|shadowrocket)"
  subscription_url: "str"
  clear_config: "bool"
stage: stable
hassio_api: true
hassio_role: default
ingress: true
ingress_port: 7890
panel_icon: "mdi:earth"
panel_title: "Proxy Service"
webui: "http://[HOST]:[PORT:7890]"
version_regex: !secret "^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\+([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?$" 