name: "代理服务"
version: "1.0.0"
slug: "proxy_service"
description: "临时代理服务，用于远程升级Home Assistant"
url: "https://github.com/symi-daguo/ha-proxy-addon"
codenotary: "symi-daguo"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
homeassistant: "2023.1.0"
homeassistant_api: true
init: false
startup: application
boot: manual
stage: stable
host_network: true
apparmor: true
privileged:
  - NET_ADMIN
  - NET_RAW
map:
  - config:rw
  - ssl:rw
ports:
  7890/tcp: 7890
  7890/udp: 7890
  7891/tcp: 7891
  7891/udp: 7891
ports_description:
  7890/tcp: "HTTP代理端口"
  7890/udp: "HTTP代理端口"
  7891/tcp: "SOCKS代理端口"
  7891/udp: "SOCKS代理端口"
options:
  subscription_type: "clash"
  subscription_url: ""
  clear_config: true
schema:
  subscription_type: "list(clash|shadowrocket)"
  subscription_url: "str"
  clear_config: "bool"
image: "ghcr.io/{arch}-proxy-service"
hassio_api: true
hassio_role: manager
ingress: true
ingress_port: 7890
panel_icon: "mdi:earth"
panel_title: "代理服务"
webui: "http://[HOST]:[PORT:7890]"
version_regex: !secret "^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\+([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?$" 